### ISSUE TITLE
Improvement: add CDN networks tagged on bgp.tools

### ISSUE THREAD

**Issue by romain-fontugne** [romain-fontugne/scapy-dns-ninja#2]
the content list should contain most of the CDN identified on bgp.tools: https://bgp.tools/tags/cdn

**Comment by ritikBhandari** [comment]
Hi @romain-fontugne !
Can I work on this issue or is this something GSOC related?

**Comment by romain-fontugne** [comment]
Yes, sure the goal is to find for each company in the list (https://bgp.tools/tags/cdn) a domain name that gives different IP addresses depending on the client location (for example  fbcdn.net for facebook)

**Comment by ritikBhandari** [comment]
@romain-fontugne I was trying to work on this issue, but I i'm curious how did you get to this example "fbcdn.net"?

**Comment by romain-fontugne** [comment]
This is very manual, I found it by looking facebook website and then I tried to ping from two different machines (one in japan one in US) to make sure that fbcdn.net is actually located at multiple places.

In this project we want to make a list of domain names that correspond to resources located at different places
